data:
  path: data/Faces
  dataset: Faces
  classes: ['CoMA']
  #path: data/Humans
  #dataset: Humans
  #classes: ['D-FAUST']
  
  train_split: train
  val_split: val
  test_split: test
  vis_split: vis

  length_sequence: 17
  n_files_per_sequence: -1
  offset_sequence: 15

  pointcloud_seq_folder: pcl_seq
  points_iou_seq_folder: points_seq
  mesh_seq_folder: mesh_seq

  points_unpackbits: false
  n_training_pcl_points: 100
  n_training_points: 512

  input_pointcloud_corresponding: false
  input_pointcloud_n: 300
  input_pointcloud_noise: 0.001


  dim: 3
  input_type: color_point_seq
  dim_color: 6
model:
  z_dim: 0
  c_dim: 512
  ode_solver: dopri5
  ode_step_size: null
  use_adjoint: true
  rtol: 0.001
  atol: 0.00001
  loss_corr: false
  loss_recon: true
  loss_corr_bw: false
  vae_beta: 0.0001
  initialize_from: null
  initialization_file_name: model_best.pt
test:
  threshold: 0.3

training:
  out_dir: out/00
  eval_sample: true
  print_every: 5
  validate_every: 20
  n_eval_points: 5000

  batch_size: 16
  batch_size_val: 1
  learning_rate: 0.0001

generation:
  interpolate: false
  correspondence: false

method: oflow

visualize:
  batch_size: 1
